# Generated by Django 4.1 on 2023-02-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_donor_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
