# Generated by Django 4.1 on 2023-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_donor_mobile_number_alter_donor_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.IntegerField(),
        ),
    ]
