# Generated by Django 4.1 on 2023-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_remove_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='has_full_access',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
    ]
