# Generated by Django 4.1 on 2023-02-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_donor_has_full_access_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
