# Generated by Django 4.1 on 2023-03-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_customuser_username_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
