# Generated by Django 4.1 on 2023-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.AddField(
            model_name='donor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
