# Generated by Django 4.1 on 2023-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_remove_donor_birthdate_donor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
