# Generated by Django 4.1 on 2023-05-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_remove_donor_last_donation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_name',
        ),
    ]
