# Generated by Django 4.1 on 2023-05-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_donation_will_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
    ]
