# Generated by Django 4.1 on 2023-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_remove_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
