# Generated by Django 4.1 on 2023-05-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_alter_donation_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
    ]
