# Generated by Django 4.1 on 2023-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_remove_donor_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
