# Generated by Django 4.1 on 2023-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_donor_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_getting_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='reting',
            field=models.IntegerField(default=50, max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='will_donate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
