# Generated by Django 4.1 on 2023-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0029_donor_is_getting_donated_donor_is_pending_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="donor", name="reting",),
        migrations.AddField(
            model_name="donor", name="rating", field=models.IntegerField(default=50),
        ),
    ]
