# Generated by Django 4.1 on 2023-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0030_remove_donor_reting_donor_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
    ]
