CITIES = [
    'Nablus', 'Jenin', 'Tulkarm', 'Qalqilya', 'Jericho', 'Ramallah', 'Bethlehem',
    'Hebron', 'Jerusalem'
]

DISTANCES = {
    'Nablus': {
        'Nablus': 0,
        'Jenin': 30,
        'Tulkarm': 40,
        'Qalqilya': 40,
        'Jericho': 50,
        'Ramallah': 25,
        'Bethlehem': 35,
        'Hebron': 45,
        'Jerusalem': 45,
    },
    'Jenin': {
        'Nablus': 30,
        'Jenin': 0,
        'Tulkarm': 35,
        'Qalqilya': 45,
        'Jericho': 55,
        'Ramallah': 40,
        'Bethlehem': 50,
        'Hebron': 55,
        'Jerusalem': 60,
    },
    'Tulkarm': {
        'Nablus': 40,
        'Jenin': 35,
        'Tulkarm': 0,
        'Qalqilya': 10,
        'Jericho': 55,
        'Ramallah': 20,
        'Bethlehem': 40,
        'Hebron': 50,
        'Jerusalem': 45,
    },
    'Qalqilya': {
        'Nablus': 40,
        'Jenin': 45,
        'Tulkarm': 10,
        'Qalqilya': 0,
        'Jericho': 60,
        'Ramallah': 35,
        'Bethlehem': 55,
        'Hebron': 65,
        'Jerusalem': 60,
    },
    'Jericho': {
        'Nablus': 50,
        'Jenin': 55,
        'Tulkarm': 55,
        'Qalqilya': 60,
        'Jericho': 0,
        'Ramallah': 60,
        'Bethlehem': 50,
        'Hebron': 65,
        'Jerusalem': 55,
    },
    'Ramallah': {
        'Nablus': 25,
        'Jenin': 40,
        'Tulkarm': 20,
        'Qalqilya': 35,
        'Jericho': 60,
        'Ramallah': 0,
        'Bethlehem': 15,
        'Hebron': 40,
        'Jerusalem': 15,
    },
    'Bethlehem': {
        'Nablus': 35,
        'Jenin': 50,
        'Tulkarm': 40,
        'Qalqilya': 55,
        'Jericho': 50,
        'Ramallah': 15,
        'Bethlehem': 0,
        'Hebron': 25,
        'Jerusalem': 10,
    },
    'Hebron': {
        'Nablus': 45,
        'Jenin': 55,
        'Tulkarm': 50,
        'Qalqilya': 65,
        'Jericho': 65,
        'Ramallah': 40,
        'Bethlehem': 25,
        'Hebron': 0,
        'Jerusalem': 20,
    },
    'Jerusalem': {
        'Nablus': 45,
        'Jenin': 60,
        'Tulkarm': 45,
        'Qalqilya': 60,
        'Jericho': 55,
        'Ramallah': 15,
        'Bethlehem': 10,
        'Hebron': 20,
        'Jerusalem': 0,
    },
}
